import React, { useState } from 'react';
import { 
  CheckCircle2, Camera, ShieldCheck, ArrowRight, ArrowLeft, X, 
  Sparkles, Layers, RefreshCw, Award, CheckCircle, FileCheck, CornerUpRight
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { CardItem, CardSubgrades, VCASlab } from '../types';
import { HolographicLabel } from './HolographicLabel';

interface GradingSubmissionWizardProps {
  card: CardItem;
  onClose: () => void;
  onComplete: (newSlab: VCASlab) => void;
}

export const GradingSubmissionWizard: React.FC<GradingSubmissionWizardProps> = ({
  card,
  onClose,
  onComplete
}) => {
  const [currentStep, setCurrentStep] = useState(1);
  const [isProcessing, setIsProcessing] = useState(false);

  // Subgrade state generated by AI
  const [subgrades, setSubgrades] = useState<CardSubgrades>({
    centering: 98,
    corners: 97,
    edges: 99,
    surface: 96,
    overall: 10
  });

  const steps = [
    { num: 1, title: 'Card Identification', desc: 'Confirm card identity & variant' },
    { num: 2, title: 'Front Flat Shot', desc: 'Overhead alignment frame' },
    { num: 3, title: 'Back Flat Shot', desc: 'Reverse side overhead' },
    { num: 4, title: 'Low-Angle Flatness', desc: 'Warping & bowing detection' },
    { num: 5, title: 'Corner Close-Ups (×4)', desc: 'Zoomed corner reticles' },
    { num: 6, title: 'Edge Close-Ups (×4)', desc: 'Print lines & edge wear' },
    { num: 7, title: 'Centering Margin Overlay', desc: 'Left/right border ratio' },
    { num: 8, title: 'AI Subgrade Analysis', desc: 'Computer vision score' },
    { num: 9, title: 'Blind QC Confirmation', desc: 'Submit to Human QC' },
    { num: 10, title: 'Slab Minted & NFC Bound', desc: 'Serial number issued' }
  ];

  const handleNextStep = async () => {
    if (currentStep === 8) {
      // Simulate AI analysis run
      setIsProcessing(true);
      await new Promise(r => setTimeout(r, 1200));
      setIsProcessing(false);
    }

    if (currentStep === 9) {
      // Complete & mint slab!
      setIsProcessing(true);
      try {
        const res = await fetch('/api/slabs/mint', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            cardId: card.id,
            subgrades,
            overallGrade: subgrades.overall,
            tier: subgrades.overall === 10 ? 'Gem Mint' : 'Standard',
            ownerUid: 'usr_vca_master_001',
            ownerName: 'Alex Vance',
            images: [card.imageUrl]
          })
        });
        const data = await res.json();
        setIsProcessing(false);
        setCurrentStep(10);
        confetti({ particleCount: 120, spread: 70, origin: { y: 0.6 } });
        if (data.slab) {
          setTimeout(() => onComplete(data.slab), 2500);
        }
      } catch (err) {
        setIsProcessing(false);
        setCurrentStep(10);
      }
      return;
    }

    if (currentStep < 10) {
      setCurrentStep(s => s + 1);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-950/85 backdrop-blur-2xl overflow-y-auto">
      <div className="glass-panel w-full max-w-4xl rounded-3xl p-6 border border-cyan-500/30 space-y-6 shadow-2xl my-auto">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
              <Award className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="font-display text-base font-extrabold text-slate-100 tracking-wider">
                  VCA GRADING SUBMISSION WIZARD
                </h2>
                <span className="px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-300 font-mono text-[10px] font-bold">
                  STEP {currentStep} OF 10
                </span>
              </div>
              <p className="text-xs text-slate-400">
                10-Stage Optical Condition Capture & Blind Human QC Submission
              </p>
            </div>
          </div>

          <button onClick={onClose} className="p-2 rounded-xl text-slate-400 hover:text-slate-100 hover:bg-slate-800">
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* STEP PROGRESS BAR */}
        <div className="space-y-1.5">
          <div className="flex items-center justify-between text-xs font-mono">
            <span className="text-cyan-300 font-bold">{steps[currentStep - 1].title}</span>
            <span className="text-slate-500">{steps[currentStep - 1].desc}</span>
          </div>
          <div className="h-2 w-full bg-slate-900 rounded-full overflow-hidden p-0.5 border border-slate-800">
            <div
              className="h-full bg-gradient-to-r from-cyan-400 via-purple-500 to-amber-400 rounded-full transition-all duration-300"
              style={{ width: `${(currentStep / 10) * 100}%` }}
            />
          </div>
        </div>

        {/* STEP CONTENT BODY */}
        <div className="min-h-[280px] flex flex-col justify-center">
          
          {/* Step 1: Confirm Card Identity */}
          {currentStep === 1 && (
            <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 flex flex-col sm:flex-row items-center gap-6">
              <img src={card.imageUrl} alt={card.name} className="w-32 h-44 object-cover rounded-xl border border-cyan-500/40 shadow-xl shrink-0" />
              <div className="space-y-2">
                <div className="px-2.5 py-1 rounded bg-emerald-500/20 text-emerald-300 font-mono text-xs font-bold inline-block">
                  CONFIRMED MATCH • 98.7% ACCURACY
                </div>
                <h3 className="font-display font-bold text-xl text-slate-100">{card.name}</h3>
                <p className="text-xs font-mono text-slate-400">{card.set} • #{card.number} • {card.variant}</p>
                <p className="text-xs text-slate-300 leading-relaxed pt-2">
                  Confirming this card for multi-angle condition scanning. In subsequent steps, VScan AI will evaluate flatness, corners, edges, and border centering.
                </p>
              </div>
            </div>
          )}

          {/* Step 2 & 3: Front / Back Flat Shot with HUD Scanline Sweep */}
          {(currentStep === 2 || currentStep === 3) && (
            <div className="relative aspect-video rounded-2xl bg-slate-950 border border-slate-800 flex items-center justify-center overflow-hidden">
              <img src={card.imageUrl} alt={card.name} className="h-full object-contain p-4 opacity-80" />
              {/* Scanline Sweep Animation */}
              <div className="absolute inset-0 bg-gradient-to-b from-cyan-400/20 via-transparent to-transparent animate-scan-line pointer-events-none" />
              <div className="absolute inset-8 border-2 border-dashed border-cyan-400/80 rounded-2xl pointer-events-none flex items-center justify-center">
                <span className="px-3 py-1 rounded-full bg-slate-950/80 border border-cyan-500/30 text-cyan-300 font-mono text-xs font-bold">
                  {currentStep === 2 ? 'FRONT FLAT OVERHEAD SHOT • SCANNING OPTICAL METRICS' : 'REVERSE SIDE OVERHEAD SHOT • SCANNING BACK SURFACE'}
                </span>
              </div>
            </div>
          )}

          {/* Step 4: Low-Angle Flatness / Warping Diagram */}
          {currentStep === 4 && (
            <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 space-y-4 text-center">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-purple-500/20 text-purple-300 border border-purple-500/40 my-2">
                <CornerUpRight className="w-8 h-8 rotate-45" />
              </div>
              <h3 className="font-display font-bold text-base text-slate-100">
                LOW-ANGLE RAKING SHOTS (WARPING & BOWING CHECK)
              </h3>
              <p className="text-xs text-slate-400 max-w-md mx-auto">
                Hold phone camera at a 20° low profile along the bottom edge & left edge under side lighting to detect foil bowing or indentations.
              </p>
              <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 font-mono text-xs text-emerald-400 font-bold inline-block">
                ✅ OPTICAL SCAN: BOWING DETECTED = 0.02mm (WELL WITHIN GEM MINT TOLERANCE)
              </div>
            </div>
          )}

          {/* Step 5 & 6: Corner / Edge Closeups */}
          {(currentStep === 5 || currentStep === 6) && (
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              {[1, 2, 3, 4].map((i) => (
                <div key={i} className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-center space-y-2">
                  <div className="relative aspect-square rounded-lg bg-slate-950 border border-cyan-500/30 flex items-center justify-center overflow-hidden">
                    <img src={card.imageUrl} alt={card.name} className="w-full h-full object-cover scale-150" />
                    <div className="absolute inset-0 border border-cyan-400/60 rounded-lg pointer-events-none" />
                  </div>
                  <div className="text-[11px] font-mono text-slate-300 font-bold">
                    {currentStep === 5 ? `CORNER #${i}` : `EDGE #${i}`}
                  </div>
                  <div className="text-[10px] font-mono text-emerald-400 font-bold">
                    98/100 CLEAN
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Step 7: Centering Overlay */}
          {currentStep === 7 && (
            <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 space-y-4 text-center">
              <div className="relative inline-block border-4 border-cyan-400 rounded-xl overflow-hidden p-2 bg-slate-950">
                <img src={card.imageUrl} alt={card.name} className="w-40 h-56 object-cover rounded" />
                <div className="absolute inset-0 border-2 border-emerald-400 border-dashed pointer-events-none" />
              </div>
              <div>
                <h4 className="font-display font-bold text-sm text-slate-100">CENTERING RATIO CHECK</h4>
                <div className="text-xs font-mono text-cyan-300 font-bold mt-1">
                  LEFT / RIGHT: 50/50 • TOP / BOTTOM: 51/49 (GEM MINT 10 CRITERIA PASS)
                </div>
              </div>
            </div>
          )}

          {/* Step 8: AI Analysis Summary */}
          {currentStep === 8 && (
            <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 space-y-4">
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <h3 className="font-display font-bold text-base text-slate-100">AI SUBGRADE ANALYSIS SUMMARY</h3>
                <span className="px-3 py-1 rounded bg-amber-500/20 text-amber-300 font-display font-black text-xs">
                  VGAS GRADE {subgrades.overall} GEM MINT
                </span>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 font-mono text-xs">
                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-slate-400">CENTERING</div>
                  <div className="text-lg font-bold text-cyan-300">{subgrades.centering}/100</div>
                </div>
                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-slate-400">CORNERS</div>
                  <div className="text-lg font-bold text-cyan-300">{subgrades.corners}/100</div>
                </div>
                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-slate-400">EDGES</div>
                  <div className="text-lg font-bold text-cyan-300">{subgrades.edges}/100</div>
                </div>
                <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
                  <div className="text-slate-400">SURFACE</div>
                  <div className="text-lg font-bold text-cyan-300">{subgrades.surface}/100</div>
                </div>
              </div>
            </div>
          )}

          {/* Step 9: Confirm & Submit */}
          {currentStep === 9 && (
            <div className="p-6 rounded-2xl bg-slate-900 border border-slate-800 space-y-4 text-center">
              <ShieldCheck className="w-12 h-12 text-cyan-400 mx-auto" />
              <h3 className="font-display font-black text-lg text-slate-100">SUBMIT TO BLIND HUMAN QC QUEUE</h3>
              <p className="text-xs text-slate-400 max-w-md mx-auto">
                Your optical capture payload will be queued for blind review by VCA Lead Inspector #04 before minting your official serial number & NTAG424 NFC binding.
              </p>
            </div>
          )}

          {/* Step 10: Slab Minted */}
          {currentStep === 10 && (
            <div className="p-6 rounded-2xl bg-gradient-to-br from-slate-900 via-slate-900 to-amber-950/40 border border-amber-500/40 text-center space-y-4">
              <Sparkles className="w-12 h-12 text-amber-400 mx-auto animate-pulse" />
              <h3 className="font-display font-black text-2xl text-amber-300">
                SERIAL VCA-000-000-004 MINTED!
              </h3>
              <p className="text-xs font-mono text-emerald-400">
                NTAG424 CMAC NFC Chip Bound • Digital Twin Ledger Record Created
              </p>
              <div className="pt-2">
                <HolographicLabel grade={10} gradeText="GEM MINT" serialNumber="VCA-000-000-004" size="lg" />
              </div>
            </div>
          )}
        </div>

        {/* FOOTER ACTIONS */}
        <div className="flex items-center justify-between border-t border-slate-800 pt-4">
          <button
            onClick={() => currentStep > 1 && setCurrentStep(s => s - 1)}
            disabled={currentStep === 1 || currentStep === 10 || isProcessing}
            className="px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 text-xs font-mono text-slate-300 hover:bg-slate-800 disabled:opacity-40"
          >
            <ArrowLeft className="w-4 h-4 inline mr-1" />
            <span>BACK</span>
          </button>

          {currentStep < 10 && (
            <button
              onClick={handleNextStep}
              disabled={isProcessing}
              className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 text-slate-950 font-display font-extrabold text-xs tracking-wider shadow-[0_0_20px_rgba(34,211,238,0.4)] hover:shadow-[0_0_30px_rgba(34,211,238,0.7)]"
            >
              {isProcessing ? (
                <RefreshCw className="w-4 h-4 animate-spin inline" />
              ) : currentStep === 9 ? (
                'MINT SLAB & BIND NFC'
              ) : (
                <>
                  <span>NEXT STEP</span>
                  <ArrowRight className="w-4 h-4 inline ml-1" />
                </>
              )}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
